### ISSUE TITLE
Simple fork cannot run on Github actions

### ISSUE THREAD

**Issue by coolboy233** [xu-cheng/cv#2]
I am deeply inpressed by the simplicity of your CV and really want to use a fork of this to build my own CV. However, I found it failed to build on Github actions without any meaningful modification. Error logs are attached in the following links:

https://github.com/coolboy233/cv/runs/3319964051

**Comment by xu-cheng** [comment]
Fixed by 1fbe303ee91f19e17eee10b013907eaa6e1e1357
